# Generated by Django 2.1 on 2018-10-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
