# Generated by Django 2.1 on 2018-10-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bevereges_burger_chinese_combo_icecream_paratha_rice_rolls_sandwitch_snacks_southindian_thali'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bevereges',
            options={'ordering': ('name',), 'verbose_name': 'beverege', 'verbose_name_plural': 'bevereges'},
        ),
    ]
