# Generated by Django 2.1 on 2018-10-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181006_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bevereges',
            options={'ordering': ('name',)},
        ),
    ]
