# Generated by Django 2.1 on 2018-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181007_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
