# Generated by Django 2.1 on 2018-10-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
